export const mockCharacters = {
  results: [
    {
      id: 1,
      name: "Character 1",
      status: "Alive",
      species: "Human",
      type: "",
      gender: "Male",
      origin: {
        name: "Earth",
        url: "url",
      },
      location: {
        name: "Somewhere",
        url: "url",
      },
      image: "",
      episode: ["se1ep1", "se2ep3"],
      url: "url",
    },
    {
      id: 2,
      name: "Character 2",
      status: "Alive",
      species: "Human",
      type: "",
      gender: "Male",
      origin: {
        name: "Earth",
        url: "url",
      },
      location: {
        name: "Somewhere",
        url: "url",
      },
      image: "",
      episode: ["se1ep1", "se2ep3"],
      url: "url",
    },
    {
      id: 3,
      name: "Character 3",
      status: "Dead",
      species: "Human",
      type: "",
      gender: "Male",
      origin: {
        name: "Earth",
        url: "url",
      },
      location: {
        name: "Somewhere",
        url: "url",
      },
      image: "",
      episode: ["se1ep1", "se2ep3"],
      url: "url",
    },
    {
      id: 4,
      name: "Character 4",
      status: "Dead",
      species: "Human",
      type: "",
      gender: "Male",
      origin: {
        name: "Earth",
        url: "url",
      },
      location: {
        name: "Somewhere",
        url: "url",
      },
      image: "",
      episode: ["se1ep1", "se2ep3"],
      url: "url",
    },
    {
      id: 5,
      name: "Character 5",
      status: "Dead",
      species: "Human",
      type: "",
      gender: "Male",
      origin: {
        name: "Earth",
        url: "url",
      },
      location: {
        name: "Somewhere",
        url: "url",
      },
      image: "",
      episode: ["se1ep1", "se2ep3"],
      url: "url",
    },
    {
      id: 6,
      name: "Character 6",
      status: "Dead",
      species: "Human",
      type: "",
      gender: "Male",
      origin: {
        name: "Earth",
        url: "url",
      },
      location: {
        name: "Somewhere",
        url: "url",
      },
      image: "",
      episode: ["se1ep1", "se2ep3"],
      url: "url",
    },
    {
      id: 7,
      name: "Character 7",
      status: "Dead",
      species: "Human",
      type: "",
      gender: "Male",
      origin: {
        name: "Earth",
        url: "url",
      },
      location: {
        name: "Somewhere",
        url: "url",
      },
      image: "",
      episode: ["se1ep1", "se2ep3"],
      url: "url",
    },
    {
      id: 8,
      name: "Character 8",
      status: "Dead",
      species: "Human",
      type: "",
      gender: "Male",
      origin: {
        name: "Earth",
        url: "url",
      },
      location: {
        name: "Somewhere",
        url: "url",
      },
      image: "",
      episode: ["se1ep1", "se2ep3"],
      url: "url",
    },
  ],
};
